### ISSUE TITLE
A Low-fidelity :  header section

### ISSUE THREAD

**Issue by BouizmouneSalma** [bouchta65/Project-Team#16]
Entant que désigner , je veut etre capable de crée Header qui contient le Logo a gauche , et a la fin an droite il y a un menu qui contient Navbar avec deux lien de navigation vers les deux page "Login" et "SignUp". Afin de facilité la navigation avec une bon experience et un beaux design.

**Comment by bouchta65** [comment]
![Image](https://github.com/user-attachments/assets/7efefc73-b349-455f-857d-00160eaa67ae)
![Image](https://github.com/user-attachments/assets/8f015348-3a10-469f-bfdf-bd2ade88a6e2)
bnssba l mobile o hta desktop
