### ISSUE TITLE
low-fidelity  : Hero section

### ISSUE THREAD

**Issue by BouizmouneSalma** [bouchta65/Project-Team#28]
En ce qui concerne l'écran mobile : 
![Image](https://github.com/user-attachments/assets/6ae3ebed-1fa3-4968-bba6-d3e0149aaa19)

Et n'oublie pas l'écran de bureau : 

![Image](https://github.com/user-attachments/assets/0dad280e-5915-4d07-a1c3-3ea4cdd24876)

Juste en basse fidélité

**Comment by mazin0eg** [comment]
mobile : ![Image](https://github.com/user-attachments/assets/d4a5c6d9-7b48-4e0e-9b84-87c78ec6eeb2)
desktop : ![Image](https://github.com/user-attachments/assets/31c94105-1a78-443c-8088-49fa123aea4e)

voila le travail demandé
