### ISSUE TITLE
low-fidelity :  login page

### ISSUE THREAD

**Issue by BouizmouneSalma** [bouchta65/Project-Team#29]
En ce qui concerne l'écran mobile : 

![Image](https://github.com/user-attachments/assets/130a5c6f-0f69-4f7a-bc7c-64f152b1bd00)

Et n'oublie pas l'écran de bureau : 

![Image](https://github.com/user-attachments/assets/27ece546-8be8-4fba-86d6-20bbf19762e7)

Juste en basse fidélité

**Comment by bouchta65** [comment]
hawlo tchofo des login pages bhalach kaykono omtnssawch thafdro 3la nafss design dyal title logo : m3a background wrah ...
