### ISSUE TITLE
low-fidelity : Offres d´Emploi

### ISSUE THREAD

**Issue by BouizmouneSalma** [bouchta65/Project-Team#32]
En ce qui concerne l'écran mobile :

![Image](https://github.com/user-attachments/assets/f502a311-af0c-4bfb-b62f-5bdf7b16e4ca)

Et n'oublie pas l'écran de bureau :

![Image](https://github.com/user-attachments/assets/56127ba9-9f77-40b8-9f88-6b99f6cdb289)

Juste en basse fidélité:

**Comment by bouchta65** [comment]
ba9i lphon page rak nssitiha khay mohamed bnssba l low-fidelity
