### ISSUE TITLE
low-fidelity : Section des entreprises de la semaine

### ISSUE THREAD

**Issue by BouizmouneSalma** [bouchta65/Project-Team#33]
**En ce qui concerne l'écran mobile :** 

![Image](https://github.com/user-attachments/assets/764a55a2-0b68-40c7-b611-0ca022aa66d2)

**Et n'oublie pas l'écran de bureau :**

  ![Image](https://github.com/user-attachments/assets/8a2ef784-0b5d-4007-8552-19fb9bc10fb9) 

Juste en basse Low fidélité

**Comment by bouchta65** [comment]
link dyal l page li at3awenk : https://www.rekrute.com/emploi-et-offres-de-recrutement-maroc-tunisie-afrique.html
