### ISSUE TITLE
A high-fidelity: Footer avec les Informations Clés

### ISSUE THREAD

**Issue by saalmahm** [bouchta65/Project-Team#9]
En tant que designer, je veux être capable de créer une section footer qui contient  text : About Us et des liens populaires, Contact Us,Entreprise , Home , Offres d'emplois ... , des icônes de réseaux sociaux, ainsi qu'une mention de Copyright, afin de fournir des informations clés et améliorer l'expérience utilisateur.

Respécter votre Maquettage : Low-fidelity 

![Image](https://github.com/user-attachments/assets/869466ed-7892-4998-b74d-2223d92598ea)

**Comment by bouchta65** [comment]
l footer ykon bhal site li chfna dak li fih zara9 olbyad

**Comment by bouchta65** [comment]
Had design ghay3awnek 

![Image](https://github.com/user-attachments/assets/08364095-33d3-4e3d-9228-0df518164303)

**Comment by mazin0eg** [comment]
mobile : ![Image](https://github.com/user-attachments/assets/1eaf07ba-a1e6-48b6-a87b-2b69f128f5cf)
desktop : ![Image](https://github.com/user-attachments/assets/e5b8bf92-0325-4037-b408-136b6f6b5d84)
le travail demende en fait merci de verifier!

**Comment by mazin0eg** [comment]
desktop : ![Image](https://github.com/user-attachments/assets/2c3ebcc9-3600-49de-818d-1c44709fe0bb)
mobile : ![Image](https://github.com/user-attachments/assets/f3f10e1a-a9f3-4937-8e05-2c2035e3884e)
voici le travail demandé
merci de varifier

**Comment by bouchta65** [comment]
![Image](https://github.com/user-attachments/assets/08364095-33d3-4e3d-9228-0df518164303)

color dyal lbutton Subscribe : #4338CA
zid l'icone dyal scroll Up : ![Image](https://github.com/user-attachments/assets/9d300c0a-17f9-4ba6-8dff-93807cb7e65e)

**Comment by mazin0eg** [comment]
desptop : ![Image](https://github.com/user-attachments/assets/32b40a9f-7533-458f-9fec-14c9433d62c7)
mobile :  ![Image](https://github.com/user-attachments/assets/68ad7d16-d415-40d6-865b-4aa61739150d)
wa barakaaaa
